/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
    
    public static void main(String[] args) throws ClassNotFoundException, SQLException{
        
        //Criando uma task
        
        //TaskController taskController = new TaskController();
        //Task task = new Task();
        //task.setName("Abrir conta");
        //task.setIdProject(2);
        //task.setDescription("Esperando no Senhor");
        //task.setIsCompleted(true);
        //task.setNotes("Vitoria");
        //taskController.Save(task);
        
        //List<Task> tasks = taskController.getAll(2);
        //System.out.println(tasks.size());
        
        // Editando um task
        
        //TaskController taskController = new TaskController();
        //Task task = new Task();
        //task.setName("Reabrido a conta");
        //task.setNotes("Reload");
        //task.setId(1);
        //taskController.updated(task);
        
        // Removendo uma task
        
        //TaskController taskController = new TaskController();
        //taskController.removebyId(2);
        
        //List<Task> tasks = taskController.getAll(2);
        //System.out.println(tasks.size());

        //Criando um projeto
        
        //ProjectController projectController = new ProjectController();   
        //Project project = new Project();
        //project.setName("Projeto teste 2");
        //project.setDescription("description 2");
        //projectController.save(project);
       
        //Editando um projeto
        
        //ProjectController projectController= new ProjectController();
        //Project project = new Project();
        //project.setId(2);
        //project.setName("Novo nome de projeto");
        //projectController.updated(project);
        
     
        //Removendo um projeto
        
        //ProjectController projectController= new ProjectController();
        //projectController.remove(1);
        
        //Listando um projeto
        
        //List<Project> projects = projectController.getAll();
        //System.out.println("Total de projetos " + projects.size());
        
        
        
        
       
        
        
        
    
    
    }
}
